name: Test Automation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    # Memungkinkan manual trigger dari GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      # Layanan MySQL untuk database
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quiz_pengupil
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, mysqli, zip
      
      - name: Start PHP server
        run: |
          # Import database schema
          if [ -d "db" ] && [ -f "db/quiz_pengupil.sql" ]; then
            mysql -h 127.0.0.1 -P 3306 -u root -proot quiz_pengupil < db/quiz_pengupil.sql
          else
            echo "Database schema tidak ditemukan, menggunakan script setup_test_db.php..."
            # Jalankan script persiapan database
            php setup_test_db.php
          fi
          
          # Start PHP server di background
          php -S localhost:8000 &
          echo "PHP server dimulai, PID: $!"
          sleep 3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Install Chrome and ChromeDriver
        run: |
          # Install Chrome
          sudo apt-get update
          sudo apt-get -y install google-chrome-stable
          
          # Tampilkan versi Chrome
          CHROME_VERSION=$(google-chrome --version)
          echo "Chrome version: $CHROME_VERSION"
          
          # Cara 1: Gunakan chromedriver-py (lebih handal)
          echo "Menginstall chromedriver-py..."
          pip install chromedriver-py
          echo "Lokasi chromedriver:"
          python -c "import chromedriver_py; print(chromedriver_py.binary_path)"
          cp $(python -c "import chromedriver_py; print(chromedriver_py.binary_path)") chromedriver
          chmod +x chromedriver
          
          # Verifikasi chromedriver
          ls -la chromedriver*
          ./chromedriver --version
          
          # Buat symlink ke folder yang diharapkan
          mkdir -p chromedriver-linux64
          cp chromedriver chromedriver-linux64/
          chmod +x chromedriver-linux64/chromedriver
      
      - name: Persiapan lingkungan pengujian
        if: always()
        run: |
          # Periksa apakah folder dan file ada
          echo "Memeriksa folder .github/config..."
          if [ -d ".github/config" ]; then
            echo "Folder .github/config ada"
          else
            echo "Folder .github/config tidak ada, membuat folder..."
            mkdir -p .github/config
          fi
          
          # Periksa apakah file setup-ci.sh ada
          if [ -f ".github/config/setup-ci.sh" ]; then
            echo "File setup-ci.sh ada"
            chmod +x .github/config/setup-ci.sh
            .github/config/setup-ci.sh
          else
            echo "File setup-ci.sh tidak ada, membuat langkah persiapan secara inline..."
            # --- Langkah persiapan inline ---
            echo "=== Setup Lingkungan CI/CD ==="
            
            # Pastikan direktori untuk screenshot ada
            mkdir -p ss_login
            mkdir -p ss_register
            
            # Periksa dependensi Python
            echo "=== Memeriksa dependensi Python ==="
            pip freeze
            
            # Periksa Chrome dan ChromeDriver
            echo "=== Memeriksa versi Chrome ==="
            google-chrome --version
            
            echo "=== Memeriksa versi ChromeDriver ==="
            if [ -f "chromedriver-linux64/chromedriver" ]; then
                chromedriver-linux64/chromedriver --version
            else
                echo "ChromeDriver tidak ditemukan di chromedriver-linux64/"
            fi
            
            # Memastikan file PHP tersedia
            echo "=== Memeriksa file PHP ==="
            ls -la *.php
          fi
        env:
          CI: "true"
      
      - name: Modifikasi skrip pengujian untuk GitHub Actions
        run: |
          # Update BASE_URL untuk mengarah ke server PHP lokal
          find . -name "test_*.py" -type f -exec sed -i 's/http:\/\/localhost\//http:\/\/localhost:8000\//g' {} \;
          find . -name "test_*.py" -exec sed -i 's/http:\/\/127.0.0.1\//http:\/\/localhost:8000\//g' {} \;
      
      - name: Verifikasi server PHP (terpisah)
        if: always()
        run: |
          # Verifikasi server berjalan
          echo "Memeriksa server PHP..."
          curl -v http://localhost:8000/ || true
          echo "Status curl: $?"
      
      - name: Debug ChromeDriver
        run: |
          ls -la chromedriver-linux64/
          chromedriver-linux64/chromedriver --version
      
      - name: Debug environment
        run: |
          echo "=== Environment Variables ==="
          echo "CI: $CI"
          echo "BASE_URL: $BASE_URL"
          echo "=== PHP Info ==="
          php -v
          echo "=== Python Info ==="
          python --version
          echo "=== Directory Structure ==="
          ls -la
          echo "=== PHP Server Status ==="
          ps aux | grep php
      
      - name: Run tests
        run: |
          # Jalankan test dengan output verbose
          python -u run_all_tests.py || {
            echo "=== TEST GAGAL! ==="
            echo "Menampilkan screenshot terakhir..."
            ls -la ss_login/ ss_register/
            exit 1
          }
        env:
          BASE_URL: http://localhost:8000
          CI: "true"
          PYTHONUNBUFFERED: "1"  # Pastikan output Python tidak di-buffer
      
      - name: Generate HTML report
        if: always()  # Selalu jalankan meskipun tes gagal
        run: python run_all_tests.py --html
        env:
          CI: "true"
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test_report_*.html
            ss_login/
            ss_register/ 